<?php

namespace VizHAAL\VisplatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends EntityRepository
{
}
